// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230209124336_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("backend.Models.Etapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReceitaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReceitaId");

                    b.ToTable("Etapas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Primeiro, faça a massa. Incline a farinha para uma tigela e adicione 300ml de água morna. Misture e reserve à temperatura ambiente durante 1 hora. Dissolva a levedura em 2 colheres de sopa de água e misture esta e 15g de sal através da massa. Cubra com película aderente e deixe em algum lugar quente para dobrar de tamanho por algumas horas. Para um sabor mais azedo, deixe na geladeira por pelo menos 8 horas e até 24 horas – quanto mais tempo você deixar, mais azedo será.",
                            ReceitaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Quando a massa estiver pronta, incline-a para uma superfície levemente enfarinhada e divida em quatro. Enrole em bolas e deixe descansar, coberto com uma toalha de chá ou filme aderente por mais uma hora.",
                            ReceitaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Agora faça o molho de tomate. Escorra um pouco do suco da lata e coloque o resto em uma tigela com o azeite, orégano e uma generosa pitada de sal, em seguida, triture tudo junto com os dedos para um molho volumoso ou blitz com um liquidificador de palito, se você quiser que seja suave. Amarre os talos de manjericão, machuque com as costas de uma faca e coloque no molho. Deixe o molho à temperatura ambiente até que seja necessário.",
                            ReceitaId = 1
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Para fazer a pizza, aqueça uma grelha até o seu cenário mais alto e pegue uma frigideira pesada. Em uma superfície enfarinhada, empurre e estique uma das bolas de massa em um círculo aproximadamente do mesmo tamanho que a frigideira. Coloque a rodada em uma assadeira enfarinhada e cubra com um quarto do molho, uma dispersão de queijo, algumas folhas de manjericão e um quarto da mussarela.",
                            ReceitaId = 1
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Pegue a panela bem quente e deslize cuidadosamente a pizza sobre ela. Cozinhe por 2 minutos, depois coloque a panela sob a grelha por mais 2 minutos até que as laterais estejam inchadas e o queijo tenha derretido. Levante em uma prancha, regue com um pouco de azeite, se quiser, depois corte em fatias e sirva enquanto faz a próxima.",
                            ReceitaId = 1
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Misture as farinhas e o fermento com uma pitada de sal em um processador de alimentos equipado com uma lâmina de massa. Despeje na água e misture em uma massa macia, em seguida, trabalhe por 1 min. Retire a massa e enrole em uma superfície levemente enfarinhada até uma volta de cerca de 30 cm de diâmetro. Levante sobre uma assadeira oleada.",
                            ReceitaId = 2
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "Espalhe os tomates enlatados sobre a massa a menos de 2 cm das bordas. Disponha os tomates cereja e as aboborinhas por cima, depois espalhe com a mussarela. Misture as alcaparras, as azeitonas e o alho, depois espalhe por cima. Regue uniformemente com o óleo. Deixe levantar por 20 minutos. Aqueça o forno a 240C/ventilador 220C/gás 9 ou a configuração mais alta.",
                            ReceitaId = 2
                        },
                        new
                        {
                            Id = 8,
                            Descricao = "Asse a pizza por 10-12 minutos até ficar crocante e dourada ao redor das bordas. Espalhe com a salsa para servir.",
                            ReceitaId = 2
                        },
                        new
                        {
                            Id = 9,
                            Descricao = "Aqueça o forno a 220C/fan 200C/gas 7. Coloque a pimenta, a abobrinha e a cebola roxa em uma assadeira antiaderente grande e regue com 1 colher de chá de azeite. Tempere bem e jogue para combinar. Asse no forno por 20 minutos até ficar macio e comece a dourar. Reservar.",
                            ReceitaId = 3
                        },
                        new
                        {
                            Id = 10,
                            Descricao = "Aqueça a grelha a médio. Tempere bem a farinha e, em uma tigela grande, misture com o óleo restante e 4-5 colheres de sopa de água para formar uma massa macia. Amasse brevemente e, em seguida, enrole em uma superfície enfarinhada em um círculo áspero de 20 cm. Transfira a massa para uma frigideira grande à prova de forno, antiaderente e frite em fogo médio por 5 minutos, até que a parte de baixo comece a dourar. Vire e cozinhe por mais 5 minutos. Espalhe o molho de tomate sobre a base, espalhe com o vegetal assado e, em seguida, polvilhe com cheddar. Grelhar a pizza por 3-4 minutos até que o queijo tenha derretido. Sirva imediatamente, fatiado em fatias, com uma grande salada verde.",
                            ReceitaId = 3
                        },
                        new
                        {
                            Id = 11,
                            Descricao = "Incline a farinha em uma tigela, em seguida, misture o fermento e 1 colher de chá de sal. Faça um poço no centro e despeje 200ml de água morna (certifique-se de que não está muito quente) junto com o óleo. Misture com uma colher de pau até ter uma massa macia e bastante molhada.",
                            ReceitaId = 4
                        },
                        new
                        {
                            Id = 12,
                            Descricao = "Incline a massa para fora em uma superfície levemente enfarinhada e amasse por 5 minutos até ficar homogêneo. Cubra com uma toalha de chá e reserve por uma hora ou mais ou menos ou até que a massa tenha inchado e dobrado de tamanho. Você também pode deixar a massa áspera e não amassada na tigela, cobrir com uma toalha de chá e deixar na geladeira durante a noite e a massa continuará a provar por conta própria.",
                            ReceitaId = 4
                        },
                        new
                        {
                            Id = 13,
                            Descricao = "Enquanto isso, faça o molho de tomate. Coloque o óleo em uma panela pequena e frite o alho brevemente (não deixe dourar), depois adicione a passata e deixe ferver tudo até o molho engrossar um pouco. Deixe esfriar.",
                            ReceitaId = 4
                        },
                        new
                        {
                            Id = 14,
                            Descricao = "Uma vez que a massa tenha subido, amasse-a rapidamente na tigela para derrubá-la de volta, depois incline-a para uma superfície levemente enfarinhada e corte em duas bolas. Enrole cada bola em uma grande lágrima que seja muito fina e com cerca de 25 cm de diâmetro (as formas de lágrima se encaixam nas assadeiras mais facilmente do que as rodadas).",
                            ReceitaId = 4
                        },
                        new
                        {
                            Id = 15,
                            Descricao = "Aqueça o forno a 240C/220C ventilador/gás 9 com uma assadeira grande dentro. Levante uma das bases em outra assadeira enfarinhada. Alise o molho sobre a base com as costas de uma colher, espalhe mais de metade da mussarela, regue com azeite e tempere. Coloque a pizza, ainda em sua assadeira, em cima da folha quente no forno e asse por 8-10 minutos até ficar crocante.",
                            ReceitaId = 4
                        },
                        new
                        {
                            Id = 16,
                            Descricao = "Pese os ingredientes para a massa em uma tigela grande e adicione 1/2 colher de chá de sal e 125ml de água morna. Misture para formar uma massa macia, depois incline para a superfície de trabalho e amasse por 5 minutos ou até que a massa pareça elástica. Limpe e unte a tigela e devolva a massa. Cubra com película aderente e deixe em algum lugar quente para subir por 1 hora, ou até que a massa tenha dobrado de tamanho.",
                            ReceitaId = 5
                        },
                        new
                        {
                            Id = 17,
                            Descricao = "Enquanto isso, faça o molho. Aqueça 1 colher de sopa de azeite em uma panela e adicione o alho. Escalfe suavemente por 30 segundos, certificando-se de que o alho não doura e, em seguida, adicione a passata. Tempere bem e borbulhe por 8-10 minutos até ter um molho rico – adicione uma pitada de açúcar se tiver um gosto um pouco azedo demais. Reservar.",
                            ReceitaId = 5
                        },
                        new
                        {
                            Id = 18,
                            Descricao = "Quando a massa tiver subido, retire o ar e enrole-a em uma base de pizza do mesmo tamanho de uma frigideira grande. Lubrifique a superfície da massa, cubra com filme aderente e, em seguida, deixe na superfície de trabalho por 15 minutos para inchar um pouco. Enquanto isso, aqueça 2 colheres de sopa de óleo na frigideira e adicione as beringelas em uma única camada (você pode ter que cozinhar em lotes). Tempere bem e cozinhe por 4-5 minutos de cada lado até ficar realmente macio e dourado. Transfira para um prato e cubra com papel alumínio para se manter aquecido.",
                            ReceitaId = 5
                        },
                        new
                        {
                            Id = 19,
                            Descricao = "Aqueça as 1 colher de sopa restantes de óleo na panela e levante cuidadosamente a massa para dentro dela. Você pode ter que remodelá-lo um pouco para se encaixar. Cozinhe em fogo baixo-médio até que a parte inferior esteja dourada e as bordas da massa estejam começando a parecer secas e ajustadas – isso deve levar cerca de 6 minutos, mas é melhor ir de olho. Vire, regue um pouco mais de óleo ao redor da borda da panela para que ele escorra sob a base da pizza e cozinhe por mais 5-6 minutos até dourar e cozinhar. Reaqueça o molho se precisar e espalhe-o sobre a base. Cubra com as beringelas quentes e pontilhar com colheres de ricota. Espalhe com hortelã e regue com um pouco de azeite extra virgem antes de servir.",
                            ReceitaId = 5
                        });
                });

            modelBuilder.Entity("backend.Models.Ingrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Produto")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Nome do Produto");

                    b.Property<double>("Qtd")
                        .HasColumnType("REAL")
                        .HasColumnName("Quantidade");

                    b.Property<int>("ReceitaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReceitaId");

                    b.ToTable("Ingredientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Produto = "Farinha de Trigo",
                            Qtd = 500.0,
                            ReceitaId = 1,
                            Tipo = "gramas"
                        },
                        new
                        {
                            Id = 2,
                            Produto = "Fermento Biológico",
                            Qtd = 7.0,
                            ReceitaId = 1,
                            Tipo = "gramas"
                        },
                        new
                        {
                            Id = 3,
                            Produto = "Tomate Fatiado",
                            Qtd = 400.0,
                            ReceitaId = 1,
                            Tipo = "gramas"
                        },
                        new
                        {
                            Id = 4,
                            Produto = "Azeite de Oliva",
                            Qtd = 1.0,
                            ReceitaId = 1,
                            Tipo = "colher de sopa"
                        },
                        new
                        {
                            Id = 5,
                            Produto = "Orégano",
                            Qtd = 0.5,
                            ReceitaId = 1,
                            Tipo = "colher de sopa"
                        },
                        new
                        {
                            Id = 6,
                            Produto = "Parmesão",
                            Qtd = 50.0,
                            ReceitaId = 1,
                            Tipo = "gramas"
                        },
                        new
                        {
                            Id = 7,
                            Produto = "Mussarela em pedaços",
                            Qtd = 200.0,
                            ReceitaId = 1,
                            Tipo = "gramas"
                        },
                        new
                        {
                            Id = 8,
                            Produto = "Farinha",
                            Qtd = 100.0,
                            ReceitaId = 2,
                            Tipo = "gramas"
                        },
                        new
                        {
                            Id = 9,
                            Produto = "Fermento Biológico",
                            Qtd = 7.0,
                            ReceitaId = 2,
                            Tipo = "gramas"
                        },
                        new
                        {
                            Id = 10,
                            Produto = "Água morna",
                            Qtd = 125.0,
                            ReceitaId = 2,
                            Tipo = "ml"
                        },
                        new
                        {
                            Id = 11,
                            Produto = "Tomate picado",
                            Qtd = 200.0,
                            ReceitaId = 2,
                            Tipo = "gramas"
                        },
                        new
                        {
                            Id = 12,
                            Produto = "Abrobrinha Fatiada",
                            Qtd = 200.0,
                            ReceitaId = 2,
                            Tipo = "gramas"
                        },
                        new
                        {
                            Id = 13,
                            Produto = "Mussarela ralada",
                            Qtd = 25.0,
                            ReceitaId = 2,
                            Tipo = "gramas"
                        },
                        new
                        {
                            Id = 14,
                            Produto = "Alcaparras",
                            Qtd = 1.0,
                            ReceitaId = 2,
                            Tipo = "colher de chá"
                        },
                        new
                        {
                            Id = 15,
                            Produto = "Azeitonas verdes ",
                            Qtd = 8.0,
                            ReceitaId = 2,
                            Tipo = ""
                        },
                        new
                        {
                            Id = 16,
                            Produto = "de álho",
                            Qtd = 1.0,
                            ReceitaId = 2,
                            Tipo = "dente"
                        },
                        new
                        {
                            Id = 17,
                            Produto = "azeite",
                            Qtd = 1.0,
                            ReceitaId = 2,
                            Tipo = "colher de chá"
                        },
                        new
                        {
                            Id = 18,
                            Produto = "Salsa picada",
                            Qtd = 2.0,
                            ReceitaId = 2,
                            Tipo = "colher de sopa"
                        },
                        new
                        {
                            Id = 19,
                            Produto = "Pimentão amarelo fatiado",
                            Qtd = 1.0,
                            ReceitaId = 3,
                            Tipo = ""
                        },
                        new
                        {
                            Id = 20,
                            Produto = "Abrobrinha fatiada",
                            Qtd = 1.0,
                            ReceitaId = 3,
                            Tipo = ""
                        },
                        new
                        {
                            Id = 21,
                            Produto = "Cebola fatiada em rodelas",
                            Qtd = 1.0,
                            ReceitaId = 3,
                            Tipo = ""
                        },
                        new
                        {
                            Id = 22,
                            Produto = "Farinha de Trigo",
                            Qtd = 225.0,
                            ReceitaId = 3,
                            Tipo = "gramas"
                        },
                        new
                        {
                            Id = 23,
                            Produto = "Azeite",
                            Qtd = 2.0,
                            ReceitaId = 3,
                            Tipo = "colher de sopa"
                        },
                        new
                        {
                            Id = 24,
                            Produto = "molho de tomate",
                            Qtd = 5.0,
                            ReceitaId = 3,
                            Tipo = "colheres de sopa"
                        },
                        new
                        {
                            Id = 25,
                            Produto = "Queijo chedar",
                            Qtd = 25.0,
                            ReceitaId = 3,
                            Tipo = "gramas"
                        },
                        new
                        {
                            Id = 26,
                            Produto = "Farinha de Trigo",
                            Qtd = 300.0,
                            ReceitaId = 4,
                            Tipo = "gramas"
                        },
                        new
                        {
                            Id = 27,
                            Produto = "Fermento Biológico",
                            Qtd = 7.0,
                            ReceitaId = 4,
                            Tipo = "gramas"
                        },
                        new
                        {
                            Id = 28,
                            Produto = "Azeite",
                            Qtd = 1.0,
                            ReceitaId = 4,
                            Tipo = "colher de sopa"
                        },
                        new
                        {
                            Id = 29,
                            Produto = "de Alho",
                            Qtd = 2.0,
                            ReceitaId = 4,
                            Tipo = "dentes"
                        },
                        new
                        {
                            Id = 30,
                            Produto = "passata",
                            Qtd = 200.0,
                            ReceitaId = 4,
                            Tipo = "ml"
                        },
                        new
                        {
                            Id = 31,
                            Produto = "mussarela",
                            Qtd = 8.0,
                            ReceitaId = 4,
                            Tipo = "fatias"
                        },
                        new
                        {
                            Id = 32,
                            Produto = "de manjericão",
                            Qtd = 1.0,
                            ReceitaId = 4,
                            Tipo = "cacho"
                        },
                        new
                        {
                            Id = 33,
                            Produto = "Farinha de trigo",
                            Qtd = 200.0,
                            ReceitaId = 5,
                            Tipo = "gramas"
                        },
                        new
                        {
                            Id = 34,
                            Produto = "Fermento biológico",
                            Qtd = 0.5,
                            ReceitaId = 5,
                            Tipo = "colher de sopa"
                        },
                        new
                        {
                            Id = 35,
                            Produto = "Açúcar",
                            Qtd = 0.25,
                            ReceitaId = 5,
                            Tipo = "colher de sopa"
                        },
                        new
                        {
                            Id = 36,
                            Produto = "de óleo",
                            Qtd = 1.0,
                            ReceitaId = 5,
                            Tipo = "colher de sopa"
                        },
                        new
                        {
                            Id = 37,
                            Produto = "de azeite",
                            Qtd = 4.0,
                            ReceitaId = 5,
                            Tipo = "colheres de sopa "
                        },
                        new
                        {
                            Id = 38,
                            Produto = "de álho",
                            Qtd = 1.0,
                            ReceitaId = 5,
                            Tipo = "dente"
                        },
                        new
                        {
                            Id = 39,
                            Produto = "passata",
                            Qtd = 200.0,
                            ReceitaId = 5,
                            Tipo = "gramas"
                        },
                        new
                        {
                            Id = 40,
                            Produto = "beringela",
                            Qtd = 1.0,
                            ReceitaId = 5,
                            Tipo = ""
                        },
                        new
                        {
                            Id = 41,
                            Produto = "ricota",
                            Qtd = 100.0,
                            ReceitaId = 5,
                            Tipo = "gramas"
                        },
                        new
                        {
                            Id = 42,
                            Produto = "de hortelã",
                            Qtd = 10.0,
                            ReceitaId = 5,
                            Tipo = "folhas"
                        },
                        new
                        {
                            Id = 43,
                            Produto = "Farinha de trigo",
                            Qtd = 200.0,
                            ReceitaId = 5,
                            Tipo = "gramas"
                        });
                });

            modelBuilder.Entity("backend.Models.Receita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Imagem Url");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Titulo da Receita");

                    b.HasKey("Id");

                    b.ToTable("Receitas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://th.bing.com/th/id/OIP.jblNW-TXQF0K0sGF3APH-gHaE8?w=267&h=180&c=7&r=0&o=5&pid=1.7",
                            Titulo = "Pizza de Margherita"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://th.bing.com/th/id/OIP.Hel2mEKk0szh-6uai4s7GQHaE7?w=235&h=180&c=7&r=0&o=5&pid=1.7",
                            Titulo = "Pizza supersaudável"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://th.bing.com/th/id/OIP.EZnothEbkm-mopx-RAMaeQAAAA?w=268&h=201&c=7&r=0&o=5&pid=1.7",
                            Titulo = "Pizza de frigideira"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://th.bing.com/th/id/OIP.9JBrOnlPio4uwPBtJZelLQHaEx?w=252&h=180&c=7&r=0&o=5&pid=1.7",
                            Titulo = "Pizza com molho caseiro"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://th.bing.com/th/id/OIP.IhgBRmB3QQ_vutQGkZG0OAHaFj?w=254&h=190&c=7&r=0&o=5&pid=1.7",
                            Titulo = "Pizza de frigideira com berinjela, ricota e hortelã"
                        });
                });

            modelBuilder.Entity("backend.Models.Etapa", b =>
                {
                    b.HasOne("backend.Models.Receita", null)
                        .WithMany("ListaEtapas")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.Ingrediente", b =>
                {
                    b.HasOne("backend.Models.Receita", null)
                        .WithMany("ListaIngredientes")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.Receita", b =>
                {
                    b.Navigation("ListaEtapas");

                    b.Navigation("ListaIngredientes");
                });
#pragma warning restore 612, 618
        }
    }
}
